app = "learn-pedestal"
primary_region = "gru"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
PORT = "8080"

[http_service]
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
max_machines_running = 1

[http_service.concurrency]
type = "requests"
soft_limit = 200
hard_limit = 250

[[vm]]
size = "shared-cpu-1x"
memory = "256MB"
